_wandb:
    value:
        cli_version: 0.30.0
        e:
            zolgpzwver72980xlx6kseippym4wep8:
                email: swu2@oxy.edu
                executable: C:\Dev\COMP395\deeplearning_env\Scripts\python.exe
                git:
                    commit: ff5d1f5b43a4c94531f421ea7a028a4959380b35
                    remote: https://github.com/CharlieWu0788/Deep-Learning.git
                host: Destine
                os: Windows-11-10.0.26300-SP0
                program: <python with no main file>
                python: CPython 3.14.5
                root: C:\Dev\COMP395
                startedAt: "2026-09-30T21:15:01.094747Z"
                writerId: zolgpzwver72980xlx6kseippym4wep8
        m: []
        python_version: 3.14.5
        t:
            "3":
                - 2
                - 13
                - 16
            "4": 3.14.5
            "5": 0.30.0
            "8":
                - 3
            "12": 0.30.0
            "13": windows-amd64
architecture:
    value: Test
epochs:
    value: 10
learning_rate:
    value: 0.02
